#########################################################################
#Q1:merge data "25_Portfolios_5x5.csv" and "F-F_Research_Data_Factors.csv"
#########################################################################



ff<-read.csv("25_Portfolios_5x5.csv")
fcts<-read.csv("F-F_Research_Data_Factors.csv")
ff2<-merge(ff, fcts, by='X')
ff3<-sapply(ff2,as.numeric)
ff3<-na.omit(ff3)


#############################################################
##Q2: Please calculate coefficients for market factors, size factor, and BM factor for 'Small.LoBM' portfolio.Which variable is dependent variable and which variable is independent variable? Are these coefficients significantly different from zero?  
##########################################################

model1<- lm(ff3[,2]~ff3[,27])
summary(model1)

model2<- lm(ff3[,2]~ff3[,27]+ff3[,28]+ff3[,29])
summary(model2)

######################################################
##Q3: Please calculate market beta for each portfolio.
######################################################

#market beta of 25 portfolios during Mar 2023 
len<-dim(ff3)[1]
beta<-mu<-rep(0,25)

for (i in 2:26){
  capmtemp<-lm(ff3[,i]~ff3[,27])
  #mu[i]<-predict(capmtemp)[len] 
  beta[i-1]<-capmtemp$coefficients[2]
}


###############################################################
#simulation of consistency 
#(omit a variable which is related to y but not related to x)
##############################################################

library(lmtest)

#keep generating hypothetical stock return (Ri), market risk premium (RmRf), size factor (SMB), book-to-market factor(HML) for 100 times
#Stock return is generated by 3-factor model, however we estimate beta by CAPM (1-factor model)
#collect beta estimation and summarize its distribution
#Note that, in practice, we do not estimate beta like this! Check Fama-Macbeth Regression for more information.

mlr4sim<-function(N){
  
  alpha<- 0.03 
  beta1<- 0.7
  beta2<- 0.5
  beta3<- 0.9  
  alphahat<-betahat<-sebetahat<-rep(0,100)
  
  for (i in 1:100){
    epsilon<-rnorm(N, mean = 0 , sd= 1)
    #epsilon<-rt(N, 5, 0)
    RmRf<- rnorm(N, mean = 0.38, sd = 4.40)
    SMB<- rnorm (N, mean = 0.42, sd = 3.17)
    HML<-rnorm(N, mean = 0.42, sd = 3.67)
    Ri<- alpha + beta1*RmRf + beta2*SMB +beta3*HML+epsilon
    
    capmtemp<- lm(Ri~RmRf)
    #ff3temp<- lm(Ri~RmRf+SMB+HML)
    alphahat[i]<-capmtemp$coef[1]
    betahat[i]<-capmtemp$coef[2]
    #setemp<-coeftest(capmtemp)
    #sebetahat<-setemp[2,2]
  }
  c(mean(betahat), sd(betahat))
}

mlr4sim(50)

#hist(betahat)
#hist((betahat-beta)/sebetahat)
#summary(alphahat)
#summary(betahat)





###########################################
#asymptotic normality of OLS 
###########################################

#dependent variable not normal

asymptsim<-function(N){
  
  alpha<- 0.03 
  beta1<- 0.7
  #beta2<- 0.5
  #beta3<- 0.9  
  alphahat<-betahat<-sebetahat<-rep(0,100)
  
  for (i in 1:100){
    epsilon<-rnorm(N, mean = 0 , sd= 0.5)
    nu<-rpois(N, lambda = 0.1)*rt(N,5,0) 
    u<-epsilon+ nu
    #u<-rlnorm(N, meanlog = 0, sdlog = 0.5)
    RmRf<- rnorm(N, mean = 0.38, sd = 4.40)
    SMB<- rnorm (N, mean = 0.42, sd = 3.17)
    HML<-rnorm(N, mean = 0.42, sd = 3.67)
    Ri<- alpha + beta1*RmRf + u
    
    capmtemp<- lm(Ri~RmRf)
    #ff3temp<- lm(Ri~RmRf+SMB+HML)
    alphahat[i]<-capmtemp$coef[1]
    betahat[i]<-capmtemp$coef[2]
    setemp<-coeftest(capmtemp)
    sebetahat<-setemp[2,2]
  }
  #c(mean(betahat), sd(betahat))
  hist((betahat-beta1)/sebetahat)
}

asymptsim(100)




########################
#FYI: quadratic programming
########################

library('quadprog')

#obtain covariance matrix

ffret<-ff3[,2:26]
cov_matrix<-cov(ffret)

#minimize the risk
#Object function: minimize w%*%sigma%*%w, subject to sum(w*beta)=0 , sum(w)=1.
Dmat<- cov_matrix
dvec<- matrix(rep(0,25),nrow=25, ncol=1)

Amat<-t(rbind(rep(1,25),beta))    #constraint matrix
bvec<-c(1,0)

weight<-solve.QP(Dmat, dvec, Amat, bvec, meq = 2)
